### ISSUE TITLE
wip-jetpack-5-dp: Xavier AGX Nvidia Mirror Issues

### ISSUE THREAD

**Issue by tjnix** [OE4T/meta-tegra#1011]
**Describe the bug**
Hi all, 

(This is really more of an Nvidia bug but I thought I'd provide some awareness in case you hadn't seen this yet).

I'm using the head of `wip-jetpack-5-dp` to build for Xavier AGX. This has been working great, however early this week, Nvidia's download mirror started having issues and a bunch of cuda related packages have been failing. For example

```
ERROR: cuda-nvcc-headers-11.4.239-1-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://repo.download.nvidia.com/jetson/common/pool/main/c/cuda-nvcc/cuda-nvcc-11-4_11.4.239-1_arm64.deb;name=main;subdir=cuda-nvcc-headers-11.4.239-1')
```

**To Reproduce**

1. Build `meta-tegra` branch `wip-jetpack-5-dp` based on `tegra194.inc`

**Additional context**
I opened a [ticket ](https://forums.developer.nvidia.com/t/repo-download-nvidia-com-issues/220120) with Nvidia and they told me that those .debs were mistakenly uploaded and that they have been removed.

My current workaround is downgrading the related packages:
```
PREFERRED_VERSION_cuda-driver = "11.4.167-1"
PREFERRED_VERSION_cuda-nvcc = "11.4.166-1"
PREFERRED_VERSION_cuda-nvcc-headers = "11.4.166-1"
PREFERRED_VERSION_cuda-cccl = "11.4.167-1"
PREFERRED_VERSION_libcublas = "11.6.5.24-1"
PREFERRED_VERSION_libnpp = "11.4.0.155-1"
PREFERRED_VERSION_libcufft = "10.6.0.71-1"
PREFERRED_VERSION_libcusparse = "11.6.0.165-1"
PREFERRED_VERSION_libcurand = "10.2.5.165-1"
PREFERRED_VERSION_cuda-cudart = "11.4.167-1"
PREFERRED_VERSION_libcusolver = "11.2.0.165-1"
PREFERRED_VERSION_cuda-nvrtc = "11.4.166-1"
PREFERRED_VERSION_cuda-nvml = "11.4.167-1"
```

**Comment by madisongh** [comment]
I've reverted the changes that upgraded those recipes, so they're back to matching NVIDIA's feed again.
