### ISSUE TITLE
Can not find the address.( https://developer.download.nvidia.com/embedded/ )

### ISSUE THREAD

**Issue by khd0801** [OE4T/meta-tegra#1015]
Could not find the address "https://developer.download.nvidia.com/embedded/" which is the address of meta-tegra/classes/l4t_bsp.bbclass L4T_URI_BASE.

Since the above address cannot be found, an error occurs in the fetch operation when building the tegra-binaries recipe.

How to modify nvidia's download address for tegra-binaries' fetch operation?

I can't find that download location on nvidia homepage....

**Comment by madisongh** [comment]
That partial URL is just used to compose a complete URL for fetching a package, and is not meant to be used on its own.  Can you provide the complete URL of what was being fetched and the specific error message reported?

**Comment by khd0801** [comment]
Thanks for your quick reply.

The url and log are as below.

url  https://developer.download.nvidia.com/embedded/L4T/r32_Release_v7.2/t186ref_release_aarch64/Tegra186_Linux_R32.7.2_aarch64.tbz2;name=l4t

error message
khd0801@khd0801:~/work/nvidia/build$ bitbake tegra-binaries
Loading cache: 100% |####################################################################################| Time: 0:00:00Loaded 1550 entries from dependency cache.
khd0801@khd0801:~/work/nvidia/build$
0Parsing of 937 .bb files complete (936 cached, 1 parsed). 1550 targets, 71 skipped, 0 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "jetson-xavier"
DISTRO               = "poky"
DISTRO_VERSION       = "3.1.17"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta                 = "dunfell:02867c90395db2ebfbcaed3d0d813b889978888c"
meta-tegra           = "dunfell-l4t-r32.4.3:bfafb644fca4c77a2599f2ce34e7c61dd96ec2f8"
meta-avikus          = "master:44036bfbf6e23a674ecb65013b5d3888c80cca67"
meta-poky
meta-yocto-bsp       = "dunfell:02867c90395db2ebfbcaed3d0d813b889978888c"

Initialising tasks: 100% |###############################################################################| Time: 0:00:00Sstate summary: Wanted 1 Found 0 Missed 1 Current 20 (0% match, 95% complete)
NOTE: Executing Tasks
WARNING: tegra-binaries-32.7.2-r0 do_fetch: Failed to fetch URL https://developer.download.nvidia.com/embedded/L4T/r32_Release_v7.2/t186ref_release_aarch64/Tegra186_Linux_R32.7.2_aarch64.tbz2;name=l4t, attempting MIRRORS if available
ERROR: tegra-binaries-32.7.2-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"; export PATH="/home/khd0801/work/nvidia/build/tmp/sysroots-uninative/x86_64-linux/usr/bin:/home/khd0801/work/nvidia/poky-dunfell/scripts:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot-native/usr/bin/aarch64-poky-linux:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot/usr/bin/crossscripts:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot-native/usr/sbin:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot-native/usr/bin:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot-native/sbin:/home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/recipe-sysroot-native/bin:/home/khd0801/work/nvidia/poky-dunfell/bitbake/bin:/home/khd0801/work/nvidia/build/tmp/hosttools"; export HOME="/home/khd0801"; /usr/bin/env wget -t 2 -T 30 --passive-ftp --no-check-certificate -P /home/khd0801/work/nvidia/build/downloads 'https://developer.download.nvidia.com/embedded/L4T/r32_Release_v7.2/t186ref_release_aarch64/Tegra186_Linux_R32.7.2_aarch64.tbz2' --progress=dot -v failed with exit code 8, no output
ERROR: tegra-binaries-32.7.2-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'https://developer.download.nvidia.com/embedded/L4T/r32_Release_v7.2/t186ref_release_aarch64/Tegra186_Linux_R32.7.2_aarch64.tbz2;name=l4t')
ERROR: Logfile of failure stored in: /home/khd0801/work/nvidia/build/tmp/work-shared/L4T-tegra-32.7.2-r0/temp/log.do_fetch.29552
ERROR: Task (/home/khd0801/work/nvidia/poky-dunfell/meta-tegra/recipes-bsp/tegra-binaries/tegra-binaries_32.7.2.bb:do_fetch) failed with exit code '1'
NOTE: Tasks Summary: Attempted 91 tasks of which 90 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/khd0801/work/nvidia/poky-dunfell/meta-tegra/recipes-bsp/tegra-binaries/tegra-binaries_32.7.2.bb:do_fetch
Summary: There was 1 WARNING message shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
khd0801@khd0801:~/work/nvidia/build$

**Comment by madisongh** [comment]
OK, so it looks like it's trying to download the L4T R32.7.2 package, but the branch of the meta-tegra layer in your build is `dunfell-l4t-r32.4.3`, which is (as the branch name implies) for L4T R32.4.3.  That's strange, since the `tegra-binaries` recipe in that branch would be for 32.4.3, not 32.7.2. Did you make some changes to the layer(s)?

If you want to use L4T R32.7.2, you should have the `dunfell` branch (with no `-l4t-...` suffix) in your build setup.  Fix that (and make sure you don't have any local modifications to `meta-tegra`), and the download should work OK.

**Comment by khd0801** [comment]
In the past, 32.4.3 was used, and some recipes of 32.7.2 were used to use deepstream.

According to your guide, after modifying the branch with dunfell, I confirmed that the download is normal.

Thanks for your help.
