### ISSUE TITLE
Will this project support meta-updater(BSP layer for updating with OSTree) ?

### ISSUE THREAD

**Issue by keguo1119** [OE4T/meta-tegra#107]

**Comment by dwalkes** [comment]
For Mender pull request, see #114

**Comment by hesmar** [comment]
@keguo1119: I am also interested in using OSTree. Were you able to make it work?

**Comment by UpsilonAudio** [comment]
Interested as well in ostree for Jetson devices, @keguo1119 any update on this ? If not I can spend time on this. Nevertheless I’m not an expert of U-Boot, I will need help to check the result

**Comment by keguo1119** [comment]
@hesmar  @UpsilonAudio , Not yet,  someone had done something: https://github.com/econsystems/meta-jetson-tx2, maybe you can see this.

**Comment by madisongh** [comment]
Closing this now.  Feel free to start a [discussion](https://github.com/OE4T/meta-tegra/discussions) if you'd like to discuss further.
