### ISSUE TITLE
L4T 32.7.3 BSP update request

### ISSUE THREAD

**Issue by acostach** [OE4T/meta-tegra#1121]
Hi,

This isn't an issue but more of a question: is the L4T 32.7.3 release support on the roadmap for meta-tegra?

Thank you

**Comment by acostach** [comment]
This is great news! Thanks a lot Matt!

**Comment by madisongh** [comment]
Both `kirkstone-l4t-r32.7.3` and `dunfell` have been updated to R32.7.3.
