### ISSUE TITLE
wrong data image filename with secure boot enabled

### ISSUE THREAD

**Issue by hesmar** [OE4T/meta-tegra#1172]
Hi, when building an image with mender and secure boot enabled, flashing is not working correctly because the filename of the data image is wrong.  The resulting tegraflash directory contains a data image file `<IMAGE_DESCRIPTOR>.dataimg` but the UDA partition defined inside the `secureflash.yml` references the file `<IMAGE_DESCRIPTOR>.dataimg.img`. 

```
...
        <partition name="UDA" type="data">
            <allocation_policy> sequential </allocation_policy>
            <filesystem_type> basic </filesystem_type>
            <size> 2097152 </size>
            <allocation_attribute> 0x808 </allocation_attribute>
            <filename> <IMAGE_DESCRIPTOR>.dataimg.img </filename>
        </partition>
...
```

So the `.img` suffix is missing in the filename. The flash tool simply skips that partition. Adapting the filename to `<IMAGE_DESCRIPTOR>.dataimg.img` works.

I am on kirkstone-r32.7.x.

**Comment by madisongh** [comment]
Which Jetson are you building for?

**Comment by hesmar** [comment]
1. I build for Jetson Nano emmc
2. I use the TEGRA_SIGNING_ARGS variable for signing during the build.

It seems the issue is in the `image_types_tegra.bbclass`:

```
tegraflash_post_sign_pkg() {
    mksparse -b ${TEGRA_BLBLOCKSIZE} --fillpattern=0 "${IMAGE_TEGRAFLASH_ROOTFS}" ${IMAGE_BASENAME}.img
    cp secureflash.xml initrd-secureflash.xml
    sed -i -e"s,APPFILE,${IMAGE_BASENAME}.img," secureflash.xml
    if [ -n "${IMAGE_TEGRAFLASH_DATA}" -a -n "${DATAFILE}" ]; then
        sed -i -e"s,DATAFILE,${DATAFILE}.img," secureflash.xml
    fi
    cat > .presigning-vars <<EOF
${@'\n'.join(d.getVar("TEGRA_SIGNING_ENV").split())}
EOF
}
```

Here it generates the secureflash.xml and appends the `.img` suffix to the DATAFILE variable but the filename of the data image is without the `.img` file extension.

**Comment by madisongh** [comment]
Yep, that looks like the problem.  The `mksparse` command that used to be in that function got lost when I refactored the per-SoC post-sign functions into a single common function.

**Comment by madisongh** [comment]
Fix has been merged, thanks
