### ISSUE TITLE
kirkstone-l4t-r32.7.x fails to boot on Jetson Nano

### ISSUE THREAD

**Issue by jhlovell** [OE4T/meta-tegra#1198]
**Describe the bug**
Demo distro fails to boot on Jetson Nano Devkit using kirkstone-l4t-r32.7.x branch. When booting I see the following error message: 

`mount: mounting /dev/root=/dev/mmcblk0p1 on /mnt failed: No such file or directory`

**To Reproduce**
1. Clone the tegra demo distro and checkout to kirkstone-l4t-r32.7.x
1. Follow the setup instructions
2. Build with bitbake argument demo-image-weston
3. Deploy to hardware using the doflash.sh script
4. Nvidia logo appears on device
5. Boot fails with the error: `mount: mounting /dev/root=/dev/mmcblk0p1 on /mnt failed: No such file or directory`

**Additional context**
I have tried the same procedure with the hardknott branch and it worked correctly. I have also successfully booted a dunfell based image. I have only encountered this error on the kirkstone-l4t-r32.7.x branch.

**Comment by madisongh** [comment]
I see... there's a typo in the `KERNEL_ROOTSPEC_DEFAULT` setting the the machine config file (and the same typo in the 2GB Nano's config file).  Not sure how I missed that.
