### ISSUE TITLE
Build and runtime issues with GNOME and GDM

### ISSUE THREAD

**Issue by VitaliiBlagodir** [OE4T/meta-tegra#1228]
**Describe the bug**
I built and run GNOME and GDM on Jetson AGX Xavier Dev Kit using `tegra-demo-distro`. There are multiple issues I solved and want to share with community.

**To Reproduce**
1. Setup `tegra-demo-distro` branch `kirkstone-l4t-r32.7.x` commit `98e8a5d` (with corresponding `meta-tegra` branch `kirkstone-l4t-r32.7.x` commit `799855c`) with the following machine and distro:

       . ./setup-env --machine jetson-agx-xavier-devkit --distro tegrademo-mender

2. Add layers

       ln -s ../repos/meta-openembedded/meta-gnome ../layers/meta-gnome
       ln -s ../repos/meta-openembedded/meta-multimedia ../layers/meta-multimedia
       bitbake-layers add-layer ../layers/meta-gnome
       bitbake-layers add-layer ../layers/meta-multimedia

4. Add to `build/conf/local.conf`

       VIRTUAL-RUNTIME_graphical_init_manager = "gdm"
       DISTRO_FEATURES:append = " polkit"
       CORE_IMAGE_BASE_INSTALL:append = " packagegroup-gnome-desktop"

5. Build with bitbake argument

       bitbake gnome-shell

6. Get build error:

```
| In file included from ../mutter-42.0/cogl/cogl/cogl-texture-2d.h:44,
|                  from ../mutter-42.0/cogl/cogl/cogl-texture-private.h:40,
|                  from ../mutter-42.0/cogl/cogl/winsys/cogl-texture-pixmap-x11-private.h:45,
|                  from ../mutter-42.0/cogl/cogl/winsys/cogl-winsys-private.h:38,
|                  from ../mutter-42.0/cogl/cogl/cogl-fence-private.h:36,
|                  from ../mutter-42.0/cogl/cogl/cogl-journal-private.h:37,
|                  from ../mutter-42.0/cogl/cogl/cogl-framebuffer-private.h:38,
|                  from ../mutter-42.0/cogl/cogl/cogl-driver.h:36,
|                  from ../mutter-42.0/cogl/cogl/cogl-context-private.h:44,
|                  from ../mutter-42.0/cogl/cogl/driver/gl/cogl-bitmap-gl.c:39:
| cogl/cogl/cogl-egl-defines.h:38:10: fatal error: EGL/eglmesaext.h: No such file or directory
|    38 | #include <EGL/eglmesaext.h>
|       |          ^~~~~~~~~~~~~~~~~~
| compilation terminated.
| ninja: build stopped: subcommand failed.
| WARNING: exit code 1 from a shell command.
```

7. Fix with patch:

```diff
diff --git a/recipes-graphics/mesa/mesa_%.bbappend b/recipes-graphics/mesa/mesa_%.bbappend
index 7d72d17f..6ea0a427 100644
--- a/recipes-graphics/mesa/mesa_%.bbappend
+++ b/recipes-graphics/mesa/mesa_%.bbappend
@@ -11,7 +11,7 @@ do_install:prepend:tegra() {
 }
 
 do_install:append:tegra() {
-    rm -rf ${D}${includedir}/EGL
+    rm -f ${D}${includedir}/EGL/eglplatform.h
 }
 
 PACKAGE_ARCH:tegra = "${TEGRA_PKGARCH}"
```

8. Build with bitbake argument

       bitbake gnome-flashback

9. Get build error

```
| No package 'xxf86vm' found
```

10. Fix with `gnome-flashback_%.bbappend`

```
DEPENDS += "libxxf86vm"
```

11. Build with bitbake argument

        bitbake demo-image-sato

12. Flash
13. GDM does not start because of permission issue and missing default xsession script
14. Fix with `gdm_%.bbappend`

```
EXTRA_OEMESON += " \
    -Dgdm-xsession=true \
"

USERADD_PARAM:${PN} =+ "--groups video,input"
```

15. Rebuild, flash and get GDM on the screen

**Comment by madisongh** [comment]
* I've pushed the fix for `mesa_%.bbappend` to the kirkstone and kirkstone-l4t-r32.7.x branches.
* The gnome-flashback dependency issue looks like a general problem that should be fixed in meta-gnome.
* The gdm config and USERADD_PARAM issues look like they might be tegra-specific, and I'd be willing to accept a patch for that (under `external/gnome-layer/recipes-gnome`), if someone is willing to maintain it.

Would you mind creating a wiki page here or over in at the [tegra-demo-distro](https://github.com/OE4T/tegra-demo-distro) repo to document this for others? Thanks!
