### ISSUE TITLE
MB2 missing partition table

### ISSUE THREAD

**Issue by oscarthorn** [OE4T/meta-tegra#1255]
Hi!

I'm not sure if this is a bug with meta-tegra or something hardware related but you seem quite knowledgeable, so I figured you might have an idea. Or know if it is a bug with meta-tegra. 

We have some xavier nx devices running dunfell and meta-tegra @ fd63b94. Some of them, 4 so far, have suddenly stopped booting. As far as we can tell they have been running fine and then suddenly on reboot we get the included error log and they wont start. We tried flashing one of them again and it has been working fine for weeks now, so it does not seem that there is any permanent hardware damage/fault to explain it.

We have now idea what's causing it so it is hard to reproduce, and we are wondering how it can happen at all? It seems this is referring to the QSPI flash but our assumption was that it would be mostly read-only? Since it is four devices (out of 50) it does not seem to be a one off fluke.

```
[0000.438] I> Welcome to MB2(TBoot-BPMP) (version: 00.00.2018.32-mobile-6fc80c72)

[...]

[0000.473] I> Boot-device: QSPI

[0000.476] I> Boot_device: QSPI_FLASH instance: 0

[0000.481] I> QSPI Flash Size = 32 MB

[0000.486] I> Qspi initialized successfully

[0000.487] I> qspi flash-0 params source = boot args

[0000.493] W> Cannot find any partition table for 00030000

[0000.498] I> Active Boot chain : 0

[0000.501] E> Cannot find partition bpmp-fw

[0000.505] E> Partition bpmp-fw not found

[0000.508] I> load/auth: execution failed

[0000.512] E> Top caller module: LOADER, error module: PARTITION_MANAGER, reason: 0x0d, aux_info: 0x00

[0000.521] I> AB warm reset
```

**Comment by ichergui** [comment]
Hey @oscarthorn 
Are you sure the flashing process went well ? Please share the host and target (serial uarl) logs. 

I'm seeing the following logs: 
```
[0000.501] E> Cannot find partition bpmp-fw
[0000.505] E> Partition bpmp-fw not found
[0000.508] I> load/auth: execution failed
```

`BPMP`  is key component. 
Also, Is secure boot enabled with your device ?

**Comment by ichergui** [comment]
Please make sure that you are using the right keys `SBK` and `PKC`

**Comment by ichergui** [comment]
@oscarthorn Is this a new hardware ? if so, please check the `FAB` and `BoardSKU`

**Comment by oscarthorn** [comment]
Would the keys being wrong not manifest immediately on first boot? How would I verify the keys on a system like this that does not boot? I think the keys are correct, according to our logs it was flashed with the correct keys (and flashing it again is fine).

Thanks, though I'm not sure you will get any error, we have several dozen more units that all work fine and even the faulty units have worked fine after flashing and only latter ended up in this state, after 1-8 weeks of use roughly.  

I don't think so, I would have to check which one it is exactly but it would be one of these. The board is another developer right now so I'll ask him to check.
```
TEGRA_BUPGEN_SPECS ?= " \
                fab=100;boardsku=0000;boardrev= \
                fab=200;boardsku=0000;boardrev= \
                fab=300;boardsku=0000;boardrev= \
                fab=301;boardsku=0000;boardrev= \
                fab=100;boardsku=0001;boardrev= \
                fab=200;boardsku=0001;boardrev= \
                fab=300;boardsku=0001;boardrev= \
                fab=301;boardsku=0001;boardrev= \
                fab=200;boardsku=0003;boardrev= \
                fab=300;boardsku=0003;boardrev= \
                fab=301;boardsku=0003;boardrev= \
"
```

**Comment by ichergui** [comment]
> I don't think so, I would have to check which one it is exactly but it would be one of these. The board is another developer right now so I'll ask him to check.
> 
> ```
> TEGRA_BUPGEN_SPECS ?= " \
>                 fab=100;boardsku=0000;boardrev= \
>                 fab=200;boardsku=0000;boardrev= \
>                 fab=300;boardsku=0000;boardrev= \
>                 fab=301;boardsku=0000;boardrev= \
>                 fab=100;boardsku=0001;boardrev= \
>                 fab=200;boardsku=0001;boardrev= \
>                 fab=300;boardsku=0001;boardrev= \
>                 fab=301;boardsku=0001;boardrev= \
>                 fab=200;boardsku=0003;boardrev= \
>                 fab=300;boardsku=0003;boardrev= \
>                 fab=301;boardsku=0003;boardrev= \
> "
> ```

Yes, please do and let me know

**Comment by oscarthorn** [comment]
Thanks, will do! I'll get back in a couple of days, he was not at home (we have a long weekend in sweden)

**Comment by oscarthorn** [comment]
@ichergui This is the boardspec for one of the faulty modules: 3668-301-0003-B.0-1-2

**Comment by madisongh** [comment]
@oscarthorn Did you figure this out?
