### ISSUE TITLE
libgcc 8.5 do_configure() fails with yesterdays Poky mickledore update

### ISSUE THREAD

**Issue by lms-jk** [OE4T/meta-tegra#1302]
Hi,

our custom Yocto build failed at the do_configure() step for libgcc 8.5:
<details>
  <summary>config.log</summary>
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by GNU C Runtime Library configure 1.0, which was
generated by GNU Autoconf 2.64.  Invocation command line was

  $ ../../../../../../../work-shared/gcc-8.5.0-r0/gcc-8.5.0/libgcc/configure --build=x86_64-linux --host=aarch64-leica-linux --target=aarch64-leica-linux --prefix=/usr --exec_prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/libexec --datadir=/usr/share --sysconfdir=/etc --sharedstatedir=/com --localstatedir=/var --libdir=/usr/lib --includedir=/usr/include --oldincludedir=/usr/include --infodir=/usr/share/info --mandir=/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-libtool-sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot --enable-version-specific-runtime-libs --with-gxx-include-dir=/usr/include/c++/8.5.0 --with-gnu-ld --enable-shared --enable-languages=c,c++ --enable-threads=posix --disable-multilib --enable-default-pie --enable-c99 --enable-long-long --enable-symvers=gnu --disable-install-libiberty --enable-libstdcxx-pch --program-prefix=aarch64-leica-linux- --program-suffix=-8.5.0 --without-local-prefix --enable-lto --disable-libssp --enable-libitm --disable-bootstrap --disable-libmudflap --with-system-zlib --with-linker-hash-style=gnu --enable-linker-build-id --with-ppl=no --with-cloog=no --enable-checking=release --enable-cheaders=c_global --without-isl --with-gxx-include-dir=/not/exist{target_includedir}/c++/8.5.0 --with-sysroot=/not/exist --with-build-sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot --without-long-double-128 libgcc_cv_powerpc_float128=no --disable-static --disable-nls --with-glibc-version=2.28 --enable-initfini-array --enable-__cxa_atexit

## --------- ##

hostname = eab330fc114b
uname -m = x86_64
uname -r = 6.3.6-arch1-1
uname -s = Linux
uname -v = #1 SMP PREEMPT_DYNAMIC Mon, 05 Jun 2023 15:12:57 +0000

/usr/bin/uname -p = x86_64
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /home/jk/pyrite/distro/build/tmp/sysroots-uninative/x86_64-linux/usr/bin
PATH: /home/jk/pyrite/distro/layers/poky/scripts
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/usr/bin/aarch64-leica-linux-8.5.0
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot/usr/bin/crossscripts
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/usr/sbin
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/usr/bin
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/sbin
PATH: /home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/bin
PATH: /home/jk/pyrite/distro/layers/poky/bitbake/bin
PATH: /home/jk/pyrite/distro/build/tmp/hosttools

## ----------- ##

configure:2268: checking build system type
configure:2282: result: x86_64-pc-linux-gnu
configure:2302: checking host system type
configure:2315: result: aarch64-leica-linux-gnu
configure:2418: checking for --enable-version-specific-runtime-libs
configure:2431: result: yes
configure:2479: checking for a BSD-compatible install
configure:2547: result: /home/jk/pyrite/distro/build/tmp/hosttools/install -c
configure:2563: checking for gawk
configure:2579: found /home/jk/pyrite/distro/build/tmp/hosttools/gawk
configure:2590: result: gawk
configure:2690: checking for aarch64-leica-linux-ar
configure:2717: result: aarch64-leica-linux-gcc-ar
configure:2782: checking for aarch64-leica-linux-lipo
configure:2812: result: no
configure:2822: checking for lipo
configure:2852: result: no
configure:2874: checking for aarch64-leica-linux-nm
configure:2901: result: aarch64-leica-linux-gcc-nm
configure:2966: checking for aarch64-leica-linux-ranlib
configure:2993: result: aarch64-leica-linux-gcc-ranlib
configure:3058: checking for aarch64-leica-linux-strip
configure:3085: result: aarch64-leica-linux-strip
configure:3147: checking whether ln -s works
configure:3151: result: yes
configure:3168: checking for aarch64-leica-linux-gcc
configure:3195: result: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot
configure:3464: checking for C compiler version
configure:3473: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot --version >&5
aarch64-leica-linux-gcc (GCC) 8.5.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
configure:3484: $? = 0
configure:3473: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot -v >&5
Using built-in specs.
COLLECT_GCC=aarch64-leica-linux-gcc
COLLECT_LTO_WRAPPER=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native/usr/bin/aarch64-leica-linux/../../libexec/aarch64-leica-linux/gcc/aarch64-leica-linux/8.5.0/lto-wrapper
aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
Target: aarch64-leica-linux
Configured with: ../../../../../../work-shared/gcc-8.5.0-r0/gcc-8.5.0/configure --build=x86_64-linux --host=x86_64-linux --target=aarch64-leica-linux --prefix=/host-native/usr --exec_prefix=/host-native/usr --bindir=/host-native/usr/bin/aarch64-leica-linux --sbindir=/host-native/usr/bin/aarch64-leica-linux --libexecdir=/host-native/usr/libexec/aarch64-leica-linux --datadir=/host-native/usr/share --sysconfdir=/host-native/etc --sharedstatedir=/host-native/com --localstatedir=/host-native/var --libdir=/host-native/usr/lib/aarch64-leica-linux --includedir=/host-native/usr/include --oldincludedir=/host-native/usr/include --infodir=/host-native/usr/share/info --mandir=/host-native/usr/share/man --disable-silent-rules --disable-dependency-tracking --with-libtool-sysroot=/host-native --enable-version-specific-runtime-libs --with-gxx-include-dir=/host-native/usr/include/c++/8.5.0 --enable-clocale=generic --with-gnu-ld --enable-shared --enable-languages=c,c++ --enable-threads=posix --disable-multilib --enable-default-pie --enable-c99 --enable-long-long --enable-symvers=gnu --disable-install-libiberty --enable-libstdcxx-pch --program-prefix=aarch64-leica-linux- --program-suffix=-8.5.0 --without-local-prefix --enable-lto --disable-libssp --enable-libitm --disable-bootstrap --disable-libmudflap --with-system-zlib --with-linker-hash-style=sysv --enable-linker-build-id --with-ppl=no --with-cloog=no --enable-checking=release --enable-cheaders=c_global --without-isl --with-gxx-include-dir=/not/exist/usr/include/c++/8.5.0 --with-sysroot=/not/exist --with-build-sysroot=/host --without-long-double-128 libgcc_cv_powerpc_float128=no --enable-poison-system-directories --with-system-zlib --disable-static --disable-nls --with-glibc-version=2.28 --enable-initfini-array --enable-__cxa_atexit
Thread model: posix
gcc version 8.5.0 (GCC) 
configure:3484: $? = 0
configure:3473: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot -V >&5
aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
aarch64-leica-linux-gcc: error: unrecognized command line option '-V'
aarch64-leica-linux-gcc: fatal error: no input files
compilation terminated.
configure:3484: $? = 1
configure:3473: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot -qversion >&5
aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
aarch64-leica-linux-gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
aarch64-leica-linux-gcc: fatal error: no input files
compilation terminated.
configure:3484: $? = 1
configure:3500: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot -o conftest  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native=   -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now conftest.c  >&5
aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
configure:3503: $? = 1
configure:3691: checking for suffix of object files
configure:3713: aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot -c  -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native=   conftest.c >&5
aarch64-leica-linux-gcc: error: unrecognized command line option '-mbranch-protection=standard'; did you mean '-fexcess-precision=standard'?
configure:3717: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Runtime Library"
| #define PACKAGE_TARNAME "libgcc"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU C Runtime Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libgcc/"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3731: error: in `/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux/libgcc':
configure:3734: error: cannot compute suffix of object files: cannot compile
See `config.log' for more details.

## ---------------- ##

ac_cv_build=x86_64-pc-linux-gnu
ac_cv_env_CC_set=set
ac_cv_env_CC_value='aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot'
ac_cv_env_CFLAGS_set=set
ac_cv_env_CFLAGS_value=' -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native= '
ac_cv_env_CPPFLAGS_set=set
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CPP_set=set
ac_cv_env_CPP_value='aarch64-leica-linux-gcc -E --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security'
ac_cv_env_LDFLAGS_set=set
ac_cv_env_LDFLAGS_value='-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now'
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=set
ac_cv_env_build_alias_value=x86_64-linux
ac_cv_env_host_alias_set=set
ac_cv_env_host_alias_value=aarch64-leica-linux
ac_cv_env_target_alias_set=set
ac_cv_env_target_alias_value=aarch64-leica-linux
ac_cv_host=aarch64-leica-linux-gnu
ac_cv_path_install='/home/jk/pyrite/distro/build/tmp/hosttools/install -c'
ac_cv_prog_AR=aarch64-leica-linux-gcc-ar
ac_cv_prog_AWK=gawk
ac_cv_prog_CC='aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot'
ac_cv_prog_NM=aarch64-leica-linux-gcc-nm
ac_cv_prog_RANLIB=aarch64-leica-linux-gcc-ranlib
ac_cv_prog_STRIP=aarch64-leica-linux-strip
gcc_cv_collect2_libs='none required'
libgcc_cv_powerpc_float128=no
lt_cv_sys_lib_dlsearch_path_spec='/usr/lib /lib'

## ----------------- ##

AR='aarch64-leica-linux-gcc-ar'
AWK='gawk'
CC='aarch64-leica-linux-gcc  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot'
CET_FLAGS=''
CFLAGS=' -O2 -pipe -g -feliminate-unused-debug-types -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native= '
CPP='aarch64-leica-linux-gcc -E --sysroot=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot  -march=armv8-a+crc -mbranch-protection=standard -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security'
CPPFLAGS=''
DEFS=''
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
EGREP=''
EXEEXT=''
GREP=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
LDFLAGS='-Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work-shared/gcc-8.5.0-r0/gcc-8.5.0=/usr/src/debug/libgcc-8/8.5.0-r0  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/gcc-8.5.0/build.aarch64-leica-linux.aarch64-leica-linux=/usr/src/debug/libgcc-8/8.5.0-r0  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fmacro-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot=  -fdebug-prefix-map=/home/jk/pyrite/distro/build/tmp/work/armv8a-leica-linux/libgcc-8/8.5.0-r0/recipe-sysroot-native=  -Wl,-z,relro,-z,now'
LIBOBJS=''
LIBS=''
LIPO=':'
LN_S='ln -s'
LTLIBOBJS=''
MAINT='#'
NM='aarch64-leica-linux-gcc-nm'
OBJEXT=''
PACKAGE_BUGREPORT=''
PACKAGE_NAME='GNU C Runtime Library'
PACKAGE_STRING='GNU C Runtime Library 1.0'
PACKAGE_TARNAME='libgcc'
PACKAGE_URL='http://www.gnu.org/software/libgcc/'
PACKAGE_VERSION='1.0'
PATH_SEPARATOR=':'
PICFLAG='-fPIC'
RANLIB='aarch64-leica-linux-gcc-ranlib'
SHELL='/bin/bash'
STRIP='aarch64-leica-linux-strip'
ac_ct_CC=''
accel_dir_suffix=''
asm_hidden_op=''
bindir='/usr/bin'
build='x86_64-pc-linux-gnu'
build_alias='x86_64-linux'
build_cpu='x86_64'
build_libsubdir='build-x86_64-linux'
build_os='linux-gnu'
build_subdir='build-x86_64-linux'
build_vendor='pc'
cpu_type=''
datadir='/usr/share'
datarootdir='${prefix}/share'
decimal_float=''
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
double_type_size=''
dvidir='${docdir}'
enable_decimal_float=''
enable_execute_stack=''
enable_shared='yes'
enable_vtable_verify='no'
exec_prefix='/usr'
extra_parts=''
fixed_point=''
force_explicit_eh_registry=''
get_gcc_base_ver=''
host='aarch64-leica-linux-gnu'
host_alias='aarch64-leica-linux'
host_cpu='aarch64'
host_noncanonical='aarch64-leica-linux'
host_os='linux-gnu'
host_subdir='.'
host_vendor='leica'
htmldir='${docdir}'
includedir='/usr/include'
infodir='/usr/share/info'
libdir='/usr/lib'
libexecdir='/usr/libexec'
libgcc_topdir='../../../../../../../work-shared/gcc-8.5.0-r0/gcc-8.5.0/libgcc/..'
localedir='${datarootdir}/locale'
localstatedir='/var'
long_double_type_size=''
mandir='/usr/share/man'
md_unwind_header=''
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr'
program_transform_name='s,x,x,'
psdir='${docdir}'
real_host_noncanonical=''
runstatedir='${localstatedir}/run'
sbindir='/usr/sbin'
set_have_cc_tls=''
set_use_emutls=''
sfp_machine_header=''
sharedstatedir='/com'
slibdir='$(libsubdir)'
sysconfdir='/etc'
target_alias='aarch64-leica-linux'
target_noncanonical='aarch64-leica-linux'
target_subdir='aarch64-leica-linux'
thread_header=''
tm_defines=''
tm_file=''
tmake_file=''
toolexecdir='$(libdir)/gcc/$(target_noncanonical)'
toolexeclibdir='$(toolexecdir)/$(gcc_version)$(MULTISUBDIR)'
unwind_header=''
vis_hide=''
with_aix_soname='aix'
with_ldbl128='no'

## ----------- ##

/* confdefs.h */
#define PACKAGE_NAME "GNU C Runtime Library"
#define PACKAGE_TARNAME "libgcc"
#define PACKAGE_VERSION "1.0"
#define PACKAGE_STRING "GNU C Runtime Library 1.0"
#define PACKAGE_BUGREPORT ""
#define PACKAGE_URL "http://www.gnu.org/software/libgcc/"

configure: exit 1
</details>

The Yocto team removed the `--enable-standard-branch-protection` flag from their gcc-configure-common.inc in [yesterdays update](https://git.yoctoproject.org/poky/commit/?h=mickledore&id=151fd33bbe25233d17cd95ea29bb72ee50172425) which looks like it caused the error.

Cheers,
Jan

**Comment by llongi** [comment]
Same happens on kirkstone with last update. The flag was moved to TUNE_CCARGS:

https://git.yoctoproject.org/poky/commit/?h=kirkstone&id=a2bf83842a72c3dfe24a824c650a2f64d3fdf1b0

which seems to break gcc-for-nvcc.

**Comment by madisongh** [comment]
I fixed this in master by updating gcc-for-nvcc to gcc 10, to make it more compatible with the newer gcc in OE-Core.

I'm not sure that's the right solution for the stable branches, though.  Filtering out the unrecognized added option in the right places (the libgcc-8 recipe and cuda.bbclass, I think) might be better.   Any preferences?

**Comment by madisongh** [comment]
> but can't find anywhere CUDA_GCCVERSION is actually used, so is this still relevant?

Probably not, since we now have the separate gcc-for-nvcc toolchain.  I'll have to go back and refresh my memory on where that came from, though.

> Does R32.7.4's CUDA 10 still strictly work only with GCC 8?

I think that's right.  The CUDA documentation describes which version(s) of the different C toolchains you can use with each CUDA version.

So for the `kirkstone-l4t-r32.7.x` branch, we'll have to just filter out the added flag.

**Comment by lms-jk** [comment]
For Mickledore, we don't have any strong preferences. We are not sure how disruptive the update to GCC 10 would be, but are open to test a mickledore with GCC 10.

Personally, I would leave GCC at version 8 since Nanbield is only a few weeks away.

**Comment by kekiefer** [comment]
I'm in favor of sticking with the status quo for both Mickledore and Kirkstone. Thanks to the analysis above, I've added the following:

```
TUNE_CCARGS:remove = "-mbranch-protection=standard"
```

to `recipes-devtools/gcc-for-nvcc/gcc-8-common.inc`, and it is at least enough to get GCC 8 compiling again.

Are we all on the same page about doing this to recover these branches?

**Comment by madisongh** [comment]
Closing this now, as the needed patches have gone into mickledore, kirkstone, and kirkstone-l4-r32.7.x.

**Comment by lms-jk** [comment]
Thanks for the quick fix, guys!
