### ISSUE TITLE
Missing UefiUpdateSecurityKeys.dtbo during tegra-minimal-initramfs.bb:do_image_cpio task

### ISSUE THREAD

**Issue by shrimpyoda** [OE4T/meta-tegra#1367]
Hi all

I'm getting errors during the `tegra-minimal-initramfs.bb:do_image_cpio` task when UEFI Secureboot is enabled. The `tegraflash.py` script complains with `FileNotFoundError: [Errno 2] No such file or directory: 'UefiUpdateSecurityKeys.dtbo'`.

I'm currently on the `kirkstone` branch and latest commit: https://github.com/OE4T/meta-tegra/commit/d92737fee5282a2604fde64f211f94ada6d35302, and my MACHINE is based on the `jetson-agx-orin-devkit.conf`.

My understand is that on the `image_types_tegra.bbclass` file, the `tegra_bootcontrol_overlay_list(d, bup=False)` function is adding the `UefiUpdateSecurityKeys.dtbo` to the list of overlays, but the same file is not being copied by the `copy_dtb_overlays()` function. The problem goes away if I modify the `copy_dtb_overlays()` function to also copy the `UefiUpdateSecurityKeys.dtbo`. However, I'm not sure if I'm missing something else. Please advise.

**Comment by madisongh** [comment]
Yep, that sounds right.  The `copy_dtb_overlays` function needs an update to cover that case.
