### ISSUE TITLE
linux-tegra kernel modify problem

### ISSUE THREAD

**Issue by durmaz54** [OE4T/meta-tegra#1385]
I am utilizing the `bitbake -c menuconfig virtual/kernel` command to make kernel configuration adjustments (such as `hostname`, `i2c` changes, etc.), followed by generating my fragment file using `bitbake -c diffconfig virtual/kernel`. I then add the following code to the `linux-tegra_%.bbappend` file I have created:

```
FILESEXTRAPATHS_prepend := "${THISDIR}/linux-tegra:"
SRC_URI += "file://fragment.cfg"
```

My appends tree:
workspace/appends/
   linux-tegra/fragment.cfg
   linux-tegra_%.bbappend

**Comment by ichergui** [comment]
Hi @durmaz54 
Could you please provide details about your issue (Linux kernel version, logs, ...) ?

**Comment by ichergui** [comment]
Could you please share the result of the following command ?
```
$ bitbake -e linux-tegra | grep -i "^SRC_"
```
also, 
Could you share the contents of the fragment file ?

**Comment by durmaz54** [comment]
My output

```
SRC_REPO="github.com/OE4T/linux-tegra-4.9;protocol=https"
SRC_URI="git://github.com/OE4T/linux-tegra-4.9;protocol=https;name=machine;branch=oe4t-patches-l4t-r32.5            file://localversion_auto.cfg                          file://fragment.cfg"

```

**Comment by ichergui** [comment]
What was the issue ? could you please share the logs ?
