### ISSUE TITLE
meta-tegra for a custom carrier board

### ISSUE THREAD

**Issue by rawnam** [OE4T/meta-tegra#1388]
Hi,

I have a custom carrier board from Neousys https://www.neousys-tech.com/en/product/product-lines/in-vehicle-computing/nru-51v-nvidia-jetson-nx-fanless-computer based on Jetson Xavier NX. I want to create an image which can be flashed onto this carrier board with all the peripherals configured appropriately. I am working with the vendor to provide support for the files needed like the bootloader or the device tree but I am not sure how to go about modifying or creating a new recipe to include those changes and build a new image for this custom carrier board

Any suggestions or thoughts would be greatly appreciated. 

Regards
Naman

**Comment by madisongh** [comment]
You could start with [this wiki page](https://github.com/OE4T/meta-tegra/wiki/Creating-a-custom-MACHINE).
