### ISSUE TITLE
Using earlycon in the cmdline.

### ISSUE THREAD

**Issue by bchoineubility** [OE4T/meta-tegra#1437]
Hi,

I have a question.

If I add earlycon  to extlinux.conf, can I see logs before boot logs on the fb console?

I hope to know exact usage of earlyconf for tegra 194.

BR,
Mark

**Comment by madisongh** [comment]
I don't think the kernel's earlycon support works for framebuffer consoles - it's too early in the boot for that, and you usually specify a UART for the earlycon output.

**Comment by bchoineubility** [comment]
@madisongh 

Thanks.  can I assign earlycon to other uart, for example uart 1?

**Comment by madisongh** [comment]
I've never tried it, but in theory it should be possible.  You might want to check the NVIDIA dev forums... there have been many threads there on the topic of using alternate UARTs for console output.

**Comment by bchoineubility** [comment]
@madisongh 

OK thanks. 

BR,
Mark
