### ISSUE TITLE
Orin and TX2 Integration fails because different branches with different packages provided (kirkstone)

### ISSUE THREAD

**Issue by roby2014** [OE4T/meta-tegra#1521]
**Describe the bug**
From what I understand, there is TX2 integration in branch `kirkstone-l4t-r32.7.x`, but Orin NX in `kirkstone` only(there is no `p3768-0000-p3767-0001` in `kirkstone-l4t-r32.7.x`.
- tx2 requires kirkstone-l4t-r32.7.x
- orin requires kirkstone 

I can compile fine for tx2, howevver, when going for the orin, I get some errors:
```
ERROR: Nothing RPROVIDES 'gstreamer1.0-omx-tegra' (but /home/ubuntu/roby/builder/build/../layers/meta-tegra-myos/recipes-myos/video/myos-video-controler.bb, /home/ubuntu/roby/builder/build/../layers/meta-myos/recipes-myos/video/myos-video-controler-dmux.bb RDEPENDS on or otherwise requires it)
NOTE: Runtime target 'gstreamer1.0-omx-tegra' is unbuildable, removing...
```

Any idea or a better approach for this?

**Comment by madisongh** [comment]
NVIDIA removed the long-deprecated OpenMAX gstreamer plugin from JetPack 5, as noted [here](https://github.com/OE4T/meta-tegra/wiki/JetPack-5.0.2-L4T-R35.1.0-Notes).  You'll need to remove that dependency from your recipes.
