### ISSUE TITLE
rtcpu device tree node disabled by initrd-flash when flashing Xavier NX

### ISSUE THREAD

**Issue by taldhous-imetrum** [OE4T/meta-tegra#1537]
When flashing an image built from meta-tegra for a Jetson Xavier NX, the rtcpu node in the kernel device tree is disabled. This stops cameras connected to the mipi port from working.

**To Reproduce**
Build demo-image-base for machine "jetson-xavier-nx-devkit-emmc".

Unpack the resulting .tar.gz file.
Note that in the device tree file "tegra194-p3668-all-p3509-0000.dtb", the node "/rtcpu@bc00000/status" is "okay".

Flash onto a device using initrd-flash.
Note that in the generated kernel device tree file "kernel_tegra194-p3668-all-p3509-0000.dtb", the node "/rtcpu@bc00000/status" is "disabled".

**Workaround**
The node is disabled by the following lines in the function "tegraflash_generate_blob" in the file "tegraflash_internal.py" (line 2933):

        if tags[0] == 'kernel_dtb' and int(values['--chip'], 0) == 0x19:
            tegraflash_disable_rce_to_dtb(filename)

Commenting out these two lines resolves the problem.

**Comment by madisongh** [comment]
Are you saying that the RTCPU is disabled just during the flashing process, or that it's also disabled once you have rebooted into the image you just flashed?

Which branch are you working from?

**Comment by taldhous-imetrum** [comment]
It is disabled once I have rebooted into the flashed image. I'm using the kirkstone branch.

**Comment by madisongh** [comment]
I have also backported the fix for this to the nanbield and kirkstone branches.  Thanks for reporting this!
