### ISSUE TITLE
Issue adding a custom `.dtb` for custom carrier (A603)

### ISSUE THREAD

**Issue by redeexpressos** [OE4T/meta-tegra#1554]
Hello, Im trying to integrate this carrier: https://wiki.seeedstudio.com/reComputer_A603_Flash_System/#download-the-peripheral-drivers

However, i'm having a little bit of trouble understanding where the files should go.
This is what I have to integrate:

```
├── bootloader
│   ├── t186ref
│   │   └── BCT
│   │       ├── tegra234-mb1-bct-padvoltage-p3767-hdmi-a03.dtsi
│   │       └── tegra234-mb1-bct-pinmux-p3767-hdmi-a03.dtsi
│   ├── tegra234-mb1-bct-gpio-p3767-dp-a03.dtsi
│   ├── tegra234-mb1-bct-gpio-p3767-hdmi-a03.dtsi
│   └── tegra234-mb2-bct-common.dtsi
└── kernel
    ├── dtb
    │   └── tegra234-p3767-0000-p3509-a02.dtb
    └── Image
```

What I did was:

- Create new machine `A603.conf` based in `p3509-a02-p3767-0000.conf`:
- Create `tegra-binaries/tegra-bootfiles` with all the `dtsi` files.
- Create `tegra-bootfiles.bbappend`
```
FILESEXTRAPATHS:prepend := "${THISDIR}/${BPN}:"
SRC_URI:append:a603= "\
    file://tegra234-mb1-bct-gpio-p3767-dp-a03.dtsi \
    file://tegra234-mb1-bct-gpio-p3767-hdmi-a03.dtsi \
    file://tegra234-mb1-bct-padvoltage-p3767-hdmi-a03.dtsi \
    file://tegra234-mb1-bct-pinmux-p3767-hdmi-a03.dtsi \
    file://tegra234-mb2-bct-common.dtsi \
"

CUSTOM_DTSI_DIR := "${THISDIR}/${BPN}"
do_install:append:a603() {
    echo "Installing custom DTSI files for ${machine}"
    install -m 0644 ${CUSTOM_DTSI_DIR}/tegra234-mb1-bct-gpio-p3767-dp-a03.dtsi ${D}${datadir}/tegraflash/
    install -m 0644 ${CUSTOM_DTSI_DIR}/tegra234-mb1-bct-gpio-p3767-hdmi-a03.dtsi ${D}${datadir}/tegraflash/
    install -m 0644 ${CUSTOM_DTSI_DIR}/tegra234-mb1-bct-padvoltage-p3767-hdmi-a03.dtsi ${D}${datadir}/tegraflash/
    install -m 0644 ${CUSTOM_DTSI_DIR}/tegra234-mb1-bct-pinmux-p3767-hdmi-a03.dtsi ${D}${datadir}/tegraflash/
    install -m 0644 ${CUSTOM_DTSI_DIR}/tegra234-mb2-bct-common.dtsi ${D}${datadir}/tegraflash/
}
```

Now I'm in trouble where `Image` and the `.dtb` should go... Since the `p3509-a02-p3767-0000.conf` conf uses a `.dtb` with the same file, and I'm not sure how to make the `a603` carrier use the `.dtb` from the vendor...

Note: Ive tried following this [article](https://github.com/OE4T/meta-tegra/wiki/Creating-a-custom-MACHINE) however there is no example with `.dtb` and `Image`...

**Comment by madisongh** [comment]
[This thread in our Matrix channel](https://matrix.to/#/!mKaltPMAHUgQwPUKcH:gitter.im/$1O5da3moy7aOXT3q2_-7G3NDO9xMUsUvamY7lKWGM_c?via=gitter.im&via=matrix.org&via=0m.ax) talks about this.  The DTB file can be provided by a separate recipe, we just don't have the wiki up-to-date with an easy how-to article.

The `Image` file is the kernel, and you should be building that from source, rather than taking the prebuilt copy from the vendor.
