### ISSUE TITLE
Disk encryption support

### ISSUE THREAD

**Issue by wavesid** [OE4T/meta-tegra#1649]
Hello

I was wondering if it's possible to build rootfs encryption in Yocto according to [documentation](https://docs.nvidia.com/jetson/archives/r36.3/DeveloperGuide/SD/Security/DiskEncryption.html#disk-encryption).

if no, please provide some guidelines on how to perform this operation using Yocto output rootfs.

Thanks

**Comment by dwalkes** [comment]
@wavesid see the discussion at https://github.com/OE4T/meta-tegra/discussions/1421#discussioncomment-7653762

There is also some discussion in the Jetpack-secureboot matrix channel at https://matrix.to/#/#nv-jetson-secureboot:gitter.im and you may find some others who can provide further guidance there.

**Comment by wavesid** [comment]
@dwalkes 
Thanks so much, will take a look!
