### ISSUE TITLE
styhead branch

### ISSUE THREAD

**Issue by sapiippo** [OE4T/meta-tegra#1728]
After commit d01401058ace3c4a11daf7184fdf0423c789c8e4, master branch in no longer compatible with meta-openembedded/styhead. Will you create separate styhead branch?

**Comment by madisongh** [comment]
We will pull a styhead branch once we merge the JetPack 6.1 update into master, and I'll deal with this mildly annoying version difference in meta-openembedded then.

**Comment by madisongh** [comment]
The [styhead](https://github.com/OE4T/meta-tegra/tree/styhead) branch is now available.
