### ISSUE TITLE
tegra-firmware confligts with linux-firmware package

### ISSUE THREAD

**Issue by sapiippo** [OE4T/meta-tegra#1729]
Including both tegra-firmware and linux-firmware packages to image causes build error using latest master meta-tegra and styhead poky.

```
Downloading file:/home/sapiippo/boot2qt/build-jetson-agx-error: check_data_file_clashes: Package linux-firmware-nvidia-tegra wants to install file /home/sapiippo/boot2qt/build-jetson-agx-orin-devkit/tmp/work/jetson_agx_orin_devkit-poky-linux/b2qt-embedded-qt6-image/1.0/rootfs/usr/lib/firmware/nvidia/tegra194/vic.bin
        But that file is already provided by package tegra-firmware-tegra234
error: check_data_file_clashes: Package linux-firmware-nvidia-tegra wants to install file /home/sapiippo/boot2qt/build-jetson-agx-orin-devkit/tmp/work/jetson_agx_orin_devkit-poky-linux/b2qt-embedded-qt6-image/1.0/rootfs/usr/lib/firmware/nvidia/tegra194/xusb.bin
        But that file is already provided by package tegra-firmware-tegra234

```

**Comment by kekiefer** [comment]
For now I would suggest not including the linux-firmware-nvidia-tegra package from linux-firmware, as this isn't something we've done in the past. How is that getting picked up for you, are you installing all of linux-firmware?

I think that we may not need the tegra194 xusb or vic firmware for t234, but this needs to be reviewed. If that's the case, moving foward, we can drop them from tegra-firmware for t234.
