### ISSUE TITLE
ERROR: libvisionworks rdepends on cuda-cudart-dev [dev-deps]

### ISSUE THREAD

**Issue by paroque28** [OE4T/meta-tegra#300]
ERROR: libvisionworks-1.6.0.500n-r0 do_package_qa: QA Issue: libvisionworks rdepends on cuda-cudart-dev [dev-deps]
ERROR: libvisionworks-1.6.0.500n-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: ..../build/tmp-glibc/work/armv8a_tegra210-wrs-linux/libvisionworks/1.6.0.500n-r0/temp/log.do_package_qa.30017
ERROR: Task (..../layers/meta-tegra/recipes-devtools/visionworks/libvisionworks_1.6.0.500n.bb:do_package_qa) failed with exit code '1'

**Comment by madisongh** [comment]
Branch?

**Comment by paroque28** [comment]
Hi Matt ,

This was on `zeus-l4t-r32.3.1`
```
IMAGE_INSTALL_append = "docker nvidia-docker nvidia-container-runtime cudnn tensorrt libvisionworks libvisionworks-sfm libvisionworks-tracking cudnn-container-csv tensorrt-container-csv libvisionworks-container-csv libvisionworks-sfm-container-csv libvisionworks-tracking-container-csv"
MACHINE='jetson-nano-qspi-sd'
```

**Comment by madisongh** [comment]
Based on the shared library info, libvisionworks should be depending on cuda-cudart (provider of libcudart.so.10.0), not cuda-cudart-dev.  Just ran a quick build myself, adding libvisionworks, and the dependency was picked up correctly.

**Comment by paroque28** [comment]
I will look into it thanks

**Comment by madisongh** [comment]
@paroque28 did you figure out what was triggering this?

**Comment by ichergui** [comment]
Hey @paroque28

**Comment by paroque28** [comment]
@ichergui  sorry, I lost the environment where I was reproducing this issue.
Let me try to replicate it. Sorry about it

**Comment by ichergui** [comment]
@paroque28 No worries.

**Comment by ichergui** [comment]
Hey @paroque28 
I have done the same test as you, it works fine to me.
Tests are done by using `zeus-l4t-r32.3.1` branch of `meta-tegra` and `Jetson TX2` as a machine.
Hope it will work for you too

**Comment by paroque28** [comment]
Hi @ichergui,
As you say, I have done the same test and it works fine to me
