### ISSUE TITLE
could not initialize GPT on image-tegra-devkit.sdcard

### ISSUE THREAD

**Issue by MJLHThomassen-Sorama** [OE4T/meta-tegra#355]
I am getting the following error while running ./dosdcard.sh:

could not initialize GPT on image-tegra-devkit.sdcard

(image-tegra-devkitis our image name)

For some strange reason, this only occurs when running the command unattended via our Teamcity buildagent. If i manually run the command on my own pc, everything succeeds.
Has anyone seen this or knows why this is happening?

**Comment by madisongh** [comment]
Does your build server have the `sgdisk` command installed on it?

**Comment by MJLHThomassen-Sorama** [comment]
> Does your build server have the `sgdisk` command installed on it?

I will check.

**Comment by madisongh** [comment]
Try using `bash -x ./dosdcard.sh` to run it, to get some more information about why it failed.  It's pretty simple up to the point you're seeing the error message for, though - it's just creating the output file and then applying the partition table.  Maybe your build server is running short on disk space or something?

**Comment by madisongh** [comment]
Nothing new on this for while, so I'll close this under the assumption that the problem got resolved.
