### ISSUE TITLE
RX buffer losses when both denver and a57 cpus are activated

### ISSUE THREAD

**Issue by anishmonachan7** [OE4T/meta-tegra#394]
Hello,
I am using GigE cameras with my jetson Tx2. The camera is connected via the eth port.
I have a problem that the capture fails at high fps. This is because the RX Ethernet buffers are not able to handle this incoming traffic on time. The following network parameters are set at maximum. It has improved the capacity but not yet to the required level. 
 ```
   net.core.netdev_max_backlog
   net.core.rmem_max
   net.core.rmem_default

```
I don't know if it is important but I could see that denver processor is in `cpu-idle` mode. Is that someway connected to the buffer loss issue? I'm using warrior-l4t-32.2 branch

How can I achieve the full capacity and avoid RX losses?

Updates
###############

I was investigating this issue, I had set different nvp modes and ran the camera again. Following are the observations
1. The camera was running with Mode 1 and mode 3  without packet losses.
2. Remaining modes are failed to handle incoming data from the Camera.
3. In the first observation for both modes 1 and 3, the `denver` cpu were inactive. It concludes that there are RX buffer losses when both `denver` and `arm 57` cpus are activated.

**Comment by anishmonachan7** [comment]
> 

> 

-

**Comment by madisongh** [comment]
You'll likely get better results by posting this on the NVIDIA Developer Forum. Some info about what the incoming network traffic is, how much there is, and if it's, for example, video that's being encoded/decoded in hardware, would probably help with getting some pointers on where to look.

**Comment by madisongh** [comment]
Looks like this is being discussed here: https://forums.developer.nvidia.com/t/tx2-eth-port-can-t-handle-high-incoming-traffic-gige-stream-issue/142979
