### ISSUE TITLE
linux-tegra-4.9 branch missing for patches-l4t-r32.4.3

### ISSUE THREAD

**Issue by MikeLoder** [OE4T/meta-tegra#422]
The dunfell-l4t-r32.4.3 branch is unable to build the associated kernel as the branch is missing in the linux-tegra-4.9 repository.

**Comment by madisongh** [comment]
The kernel branch name changed to `patches-l4t-r32.4` for the 32.4.3 release, to parallel the branch name change NVIDIA made upstream.  The linux-tegra_4.9 recipe does use the new branch name, so check to see if you have any bbappends or other overrides that could be interfering.

**Comment by MikeLoder** [comment]
Thanks for the quick response, sorry for the confusion. I have to say you have done some excellent work on this repo and its helped me tremendously. Thanks for your hard work.
