### ISSUE TITLE
libnvidia-container-tools embeds build information

### ISSUE THREAD

**Issue by madisongh** [OE4T/meta-tegra#429]
Originally reported [here](https://github.com/madisongh/tegra-test-distro/issues/2), the makefiles for libnvidia-container-tools generate a header file that embeds information about the compiler, platform, and date of the build in a way that doesn't always work well

* Compiler name extraction doesn't handle `$(CC)` being multiple words with options
* The date setting breaks reproducible builds
* PLATFORM is set using `uname -m`, which isn't correct for cross builds
* The inclusion of compiler flags also breaks reproducible builds by embedding build host paths.

**Comment by outbackdingo** [comment]
Fedora 32 Silver Blue Default shell is ZSHELL ... never had issues compiling yocto/oe on it .... and Thanks!
cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/10/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
and envSSH_AGENT_PID=1537
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=KDE
GDK_CORE_DEVICE_EVENTS=1
XCURSOR_THEME=breeze_cursors
TILIX_ID=9843a320-755a-47d0-b66d-1c087e6a797e
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=dingo
HOSTNAME=localhost.localdomain
OLDPWD=/var/home/dingo
HISTSIZE=50000
KDE_SESSION_VERSION=5
KDEDIRS=/usr
HOME=/var/home/dingo
XDG_MENU_PREFIX=kf5-
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_VTNR=1
XDG_SEAT=seat0
DESKTOP_SESSION=/usr/share/xsessions/plasma
XDG_CONFIG_DIRS=/etc/xdg:/usr/share/kde-settings/kde-profile/default/xdg
VTE_VERSION=6003
XDG_DATA_DIRS=/var/home/dingo/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
XDG_SESSION_DESKTOP=KDE
KDE_SESSION_UID=1000
MAIL=/var/spool/mail/dingo
QT_AUTO_SCREEN_SCALE_FACTOR=0
LOGNAME=dingo
PATH=/var/home/dingo/tegra-test-distro/layers/meta-testdistro/scripts:/var/home/dingo/tegra-test-distro/layers/scripts:/var/home/dingo/tegra-test-distro/repos/poky/bitbake/bin:/var/home/dingo/tegra-demo-distro/layers/meta-tegrademo/scripts:/var/home/dingo/tegra-demo-distro/layers/scripts:/var/home/dingo/tegra-demo-distro/repos/poky/bitbake/bin:/var/home/dingo/tegra-demo-distro/layers/meta-tegrademo/scripts:/var/home/dingo/tegra-demo-distro/layers/meta-tegrademo/scripts:/usr/local/bin:/usr/bin:/bin:/var/home/dingo/bin:/usr/local/sbin:/usr/sbin
XDG_RUNTIME_DIR=/run/user/1000
_=/usr/bin/env
SHELL=/usr/bin/zsh
KDEWM=/usr/bin/xmonad
XDG_SESSION_TYPE=x11
XDG_SESSION_ID=1
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
HISTCONTROL=ignoredups
KDE_FULL_SESSION=true
SHLVL=1
XAUTHORITY=/var/home/dingo/.Xauthority
COLORTERM=truecolor
PWD=/var/home/dingo/tegra-test-distro
DISPLAY=:0
XDG_SESSION_CLASS=user
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
TERM=xterm-256color
LS_COLORS=rs=0:di=38;5;33:ln=38;5;51:mh=00:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=01;37;41:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;40:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.zst=38;5;9:*.tzst=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.wim=38;5;9:*.swm=38;5;9:*.dwm=38;5;9:*.esd=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.mjpg=38;5;13:*.mjpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.webp=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
P9K_TTY=old
ZSH=/var/home/dingo/.oh-my-zsh
UPDATE_ZSH_DAYS=13
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
P9K_SSH=0
MANPATH=/usr/local/man:
BBPATH=/var/home/dingo/tegra-test-distro/build
BUILDDIR=/var/home/dingo/tegra-test-distro/build
BB_ENV_EXTRAWHITE= ALL_PROXY BBPATH_EXTRA BB_LOGCONFIG BB_NO_NETWORK BB_NUMBER_THREADS BB_SETSCENE_ENFORCE BB_SRCREV_POLICY DISTRO FTPS_PROXY FTP_PROXY GIT_PROXY_COMMAND HTTPS_PROXY HTTP_PROXY MACHINE NO_PROXY PARALLEL_MAKE SCREENDIR SDKMACHINE SOCKS5_PASSWD SOCKS5_USER SSH_AGENT_PID SSH_AUTH_SOCK STAMPS_DIR TCLIBC TCMODE all_proxy ftp_proxy ftps_proxy http_proxy https_proxy no_proxy 



Target: x86_64-redhat-linux
Configured with: ../configure --enable-bootstrap --enable-languages=c,c++,fortran,objc,obj-c++,ada,go,d,lto --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-shared --enable-threads=posix --enable-checking=release --enable-multilib --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-gcc-major-version-only --with-linker-hash-style=gnu --enable-plugin --enable-initfini-array --with-isl --enable-offload-targets=nvptx-none --without-cuda-driver --enable-gnu-indirect-function --enable-cet --with-tune=generic --with-arch_32=i686 --build=x86_64-redhat-linux
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20200723 (Red Hat 10.2.1-1) (GCC) 

uname -a
Linux localhost.localdomain 5.8.7-200.fc32.x86_64 #1 SMP Mon Sep 7 15:26:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
