### ISSUE TITLE
Dunfell-L4T-R32.4.3 compatibility with JetPack releases

### ISSUE THREAD

**Issue by chhg82** [OE4T/meta-tegra#457]
Following basic questions:

With which JetPack version is the Dunfell-L4T-R32.4.3 branch compatible? Is it backward compatible with e.g. cuda 10.0 (JetPack 4.3) for Jetson Xavier or is it just for JetPack 4.4? Does 4.4.1 contain the same download content as 4.4?

Thanks a lot!

**Comment by dwalkes** [comment]
@chhg82 see https://github.com/OE4T/meta-tegra/wiki/Which-branch-should-I-use%3F - Dunfell-L4T-R32.4.3 uses Jetpack 4.4. For the summary of differences beteen 4.4.1 and 4.4 see https://github.com/OE4T/meta-tegra/wiki/L4T-R32.4.4-Notes and for the full merge request see https://github.com/OE4T/meta-tegra/pull/452
