### ISSUE TITLE
no providers found in RDEPENDS_cuda-nvgraph

### ISSUE THREAD

**Issue by dwalkes** [OE4T/meta-tegra#472]
I'm trying to setup a branch to update https://github.com/OE4T/tegra-demo-distro to master branches with `testdistro-mender` builds, and I'm seeing this error attempting to build `demo-image-base`.  I've verified my layers at https://github.com/BoulderAI/tegra-demo-distro/tree/master-next/repos match what I see on master at https://github.com/madisongh/tegra-test-distro/tree/master/repos

```
ERROR: cuda-nvgraph-10.2.89-1-r0 do_package_qa: QA Issue: /usr/local/cuda-10.2/lib/libnvgraph.so.10.2.89 contained in package cuda-nvgraph requires libcurand.so.10(libcurand.so.10)(64bit), but no providers found in RDEPENDS_cuda-nvgraph? [file-rdeps]
ERROR: cuda-nvgraph-10.2.89-1-r0 do_package_qa: QA Issue: /usr/local/cuda-10.2/lib/libnvgraph.so.10.2.89 contained in package cuda-nvgraph requires libcusolver.so.10(libcusolver.so.10)(64bit), but no providers found in RDEPENDS_cuda-nvgraph? [file-rdeps]
ERROR: cuda-nvgraph-10.2.89-1-r0 do_package_qa: QA Issue: /usr/local/cuda-10.2/lib/libnvgraph.so.10.2.89 contained in package cuda-nvgraph requires libcurand.so.10()(64bit), but no providers found in RDEPENDS_cuda-nvgraph? [file-rdeps]
ERROR: cuda-nvgraph-10.2.89-1-r0 do_package_qa: QA Issue: /usr/local/cuda-10.2/lib/libnvgraph.so.10.2.89 contained in package cuda-nvgraph requires libcusolver.so.10()(64bit), but no providers found in RDEPENDS_cuda-nvgraph? [file-rdeps]
ERROR: cuda-nvgraph-10.2.89-1-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: Logfile of failure stored in: /build/tegra-demo-distro/build/tmp/work/armv8a_tegra-oe4t-linux/cuda-nvgraph/10.2.89-1-r0/temp/log.do_package_qa.12853
ERROR: Task (/build/tegra-demo-distro/layers/meta-tegra/recipes-devtools/cuda/cuda-nvgraph_10.2.89-1.bb:do_package_qa) failed with exit code '1'
```
`bitbake -e cuda-nvgraph` shows:
```
RDEPENDS_cuda-nvgraph="tegra-libraries cuda-nvgraph-container-csv"
```
and all the dependencies look like they are setup exactly the same way in https://github.com/OE4T/meta-tegra/blob/master/recipes-devtools/cuda/cuda-libraries_10.2.89-1.bb#L29.

I'm guessing I need some path magic somewhere but I'm not coming up with where, looking for some direction from anyone who has solved similar problems before.  I noticed https://github.com/OE4T/meta-tegra/issues/360 which looks similar but appears to be a different issue.

**Comment by madisongh** [comment]
Yeah, the packaging code isn't finding the providing packages for those libraries, but `libcuda-nvgraph` is linked against them.  Not sure why I haven't seen this before in my builds.
