### ISSUE TITLE
jetson-xavier-nx-devkit* on dunfell ?

### ISSUE THREAD

**Issue by om26er** [OE4T/meta-tegra#496]
It seems the dunfell branch does not support Xavier NX based machines. Are there plans to support that ? Would it be acceptable if I do a PR for that ?

**Comment by madisongh** [comment]
The dunfell branch is based off L4T R32.3.1, which didn't have support for Xavier NX. Could you use the dunfell-l4t-r32.4.3 branch instead?

**Comment by om26er** [comment]
Yeah that worked. Thanks for the help.
