### ISSUE TITLE
Xavier NX: Flashing to eMMC stuck

### ISSUE THREAD

**Issue by om26er** [OE4T/meta-tegra#497]
We had our custom yocto distro, today I added support for Xavier NX, I was able to produce the image successfully, however I am not able to flash the image to the eMMC, it "hangs". Attached are the logs.
[tegra-flash.log](https://github.com/OE4T/meta-tegra/files/5569269/tegra-flash.log)

**Comment by madisongh** [comment]
A couple of questions:
* Is the device really a Xaver NX production (eMMC) module installed in a Xavier NX dev kit or Nano carrier? If it's actually a standard dev kit, then there is no eMMC, and you should use the `jetson-xavier-nx-devkit` machine configuration.
* Do you have a serial console cable connected?  Seeing what the device is doing during the flashing process could help with troubleshooting.

**Comment by om26er** [comment]
You are right, I had to use the jetson-xavier-nx-devkit for the flashing to "proceed" a bit. But now I am faced with another issue. Attached the logs
[tegra2.log](https://github.com/OE4T/meta-tegra/files/5569460/tegra2.log)

"End sector for RECROOTFS, expected at: 30253022, actual: 30369575"

**Comment by om26er** [comment]
The above was an issue with my sdcard, I tried another one and it seems to be flashing fine now.

Is there a way to flash the image on eMMC instead ?

**Comment by madisongh** [comment]
The NX module with on-board eMMC is a different part.  The module in the dev kit only has the SDcard slot.
