### ISSUE TITLE
Task do_populate_sdk in .... rdepends upon non-existent task do_package_write_deb

### ISSUE THREAD

**Issue by MehdiJaiem502** [OE4T/meta-tegra#516]
Hello 

I am trying to build an Image based on the Yocto Project for my stm32mp157c-DK2 according to [st-wiki].(https://wiki.st.com/stm32mpu/wiki/STM32MP1_Distribution_Package#Building_the_OpenSTLinux_distribution)

When I try to build the image I get the following error.
`ERROR: Task do_populate_sdk in /home/mehdi/Distribution-Package/openstlinux-5.4-dunfell-mp1-20-11-12/layers/meta-st/meta-st-openstlinux/recipes-st/images/st-image-weston.bb rdepends upon non-existent task do_package_write_deb in /home/mehdi/Distribution-Package/openstlinux-5.4-dunfell-mp1-20-11-12/layers/meta-st/meta-st-openstlinux/recipes-st/images/st-image-weston.bb
ERROR: Command execution failed: 1`

What did I miss or what did I do wrong in my local.conf file ?

Best regards.

I can share with you the content of the file:

[local.conf.txt](https://github.com/OE4T/meta-tegra/files/5673875/local.conf.txt)

**Comment by dwalkes** [comment]
> I am trying to build an Image based on the Yocto Project for my stm32mp157c-DK2

I think you may be posting in the wrong place?  This project is for the meta-tegra layer for NVIDIA Jetson devices.

**Comment by MehdiJaiem502** [comment]
> > I am trying to build an Image based on the Yocto Project for my stm32mp157c-DK2
> 
> I think you may be posting in the wrong place? This project is for the meta-tegra layer for NVIDIA Jetson devices.

I opened too much tabs sorry! Is it possible to delete the issue ?

**Comment by madisongh** [comment]
No sweat, @MehdiJaiem502 .  We can just close it.
