### ISSUE TITLE
Using OpenGL ES instead of OpenGL Desktop in Yocto Distro

### ISSUE THREAD

**Issue by mozcelikors** [OE4T/meta-tegra#606]
Hi,
A colleague of mine is working with low level OpenGL libraries in order to change some of the display behavior on Jetson Xavier NX. Qt apps are being compiled with the following libraries:

`LIBS          = $(SUBLIBS) -lEGL -lGLESv2 /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Quick.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5OpenGL.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Widgets.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Gui.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5QmlModels.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Qml.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Network.so /opt/poky/3.2+snapshot/sysroots/armv8a-poky-linux/usr/lib/libQt5Core.so -lGL -lpthread`

Here, final -lGL library is added automatically, we believe it is because of the Qt configuration. When we look at the config.summary, we see that the desktop OpenGL is used.

```
OpenGL:
    Desktop OpenGL ....................... yes
    OpenGL ES 2.0 ........................ no
    OpenGL ES 3.0 ........................ no
    OpenGL ES 3.1 ........................ no
    OpenGL ES 3.2 ........................ no
```
Is there a way to switch to Open GL ES 3.2 in a proper way using Yocto distro?, e.g. using PACKAGECONFIG and DISTRO_FEATURES variables. Something like;

```
DISTRO_FEATURES_remove = "x11 wayland"
PACKAGECONFIG_qtbase_remove = "gl"
```

Any help is appreciated.

**Comment by kekiefer** [comment]
I am using Qt with OpenGL ES, but it has been quite some time since configuring it. Try adding `gles2` to `DISTRO_FEATURES`, and `eglfs gles2` to `PACKAGECONFIG_qtbase`, and see if this gets the configuration set up better.
