### ISSUE TITLE
Recipe for adding new kernel module to meta-tegra

### ISSUE THREAD

**Issue by mozcelikors** [OE4T/meta-tegra#608]
Hi, I would like to integrate https://github.com/umlaeute/v4l2loopback to Yocto distro.
Is there an example kernel module recipe that will work with meta-tegra that I could base my work off of.

As starting point, currently I have:

```
SUMMARY = "Kernel loadable module v4l2loopback"
LICENSE = "CLOSED"

SRC_URI = "git://github.com/umlaeute/v4l2loopback.git;branch=main"

SRCREV = "f62fb9076b6313e5eb82fdcaceadb6b3052f346e"

S = "${WORKDIR}/git"

inherit module
```
However this is not compiled against the kernel of the meta-tegra. It uses my own PC headers ( `/usr/src/linux-headers-5.8.0-44-generic/` ) currently.

Thanks for pointers in advance.

**Comment by madisongh** [comment]
There's nothing tegra-specific about how to build out-of-tree kernel modules, just follow the usual OE/Yocto approach.  For an example, see [this sample recipe](https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta-skeleton/recipes-kernel/hello-mod).
