### ISSUE TITLE
SD card image for Jetson Xavier AGX

### ISSUE THREAD

**Issue by chhg82** [OE4T/meta-tegra#637]
How can I generate an SD card image on dunfell-l4t-r32.4.3 for xavier agx?

**Comment by madisongh** [comment]
AGX Xavier doesn't come with an SDcard slot.  If you mean Xavier NX, there's some info on [this wiki page](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit).

**Comment by chhg82** [comment]
I use agx xavier developer kit. You're right, on the som is no slot but on the evalboard...

**Comment by madisongh** [comment]
Well, so there is... I've had mine for a long time, and I never noticed that before.  I'm not sure you can boot from it, though.  I've never seen anything in L4T that supports such a setup on the AGX.

**Comment by chhg82** [comment]
With nvidia sdk i got it running with: sudo ./flash.sh jetson-xavier mmcblk1p1. But how can I do it with meta-tegra?

**Comment by ichergui** [comment]
Hey @chhg82 @madisongh

I confirm that the `Jetson Xavier AGX` have a SDcard slot. I didn't try to boot by using the SDcard tbh.

![IMG_8844](https://user-images.githubusercontent.com/15719516/112146719-d1d9bc00-8bd3-11eb-9c7d-5c02bbcc496b.jpg)

Here is some interesting links:

From Nvidia Dev talk [does-jetson-agx-xavier-support-boot-from-sd](https://forums.developer.nvidia.com/t/does-jetson-agx-xavier-support-boot-from-sd/65872)

[Flashing Jetson Xavier AGX](https://developer.ridgerun.com/wiki/index.php?title=Xavier/Flashing_the_Board)

I will experiment this and I will let you know.

**Comment by chhg82** [comment]
Hi @ichergui 

Thanks for experimenting! Any news about it?

**Comment by ichergui** [comment]
Sorry @chhg82 
I was quite busy these days. I will try later and give a feedback.
I will double check with @madisongh if script `make-sdcard` provide by tegraflash package make our lifre easy to create the right SDcard to boot with.

**Comment by koansoftware** [comment]
I did it on June 2020 and now I don't have the board here, so I hope to remember correctly.
[NVIDIA Jetson AGX Xavier with Yocto Project](https://koansoftware.com/yocto-project-on-nvidia-jetson-agx-xavier/)

**Flashing Linux on the eMMC**
Enable recovery mode, then run
`sudo ./flash.sh jetson-xavier mmcblk0p1`

**Flashing Linux on the microSD**
Enable recovery mode, then run
`sudo ./flash.sh jetson-xavier mmcblk1p1`

**Comment by ichergui** [comment]
Thanks @koansoftware

The `meta-tegra` layer provides scripts `doflash.sh` and `dosdcard.sh` for Jetsons platform that have only eMMC (production devices) and  the SDcard (Development kit) respectively.  The Jetson Xavier AGX devkit is an exception which have both (eMMC and SDcard).

The Jetson Xavier AGX tegraflash package include `doflash.sh` and `make-sdcard` scripts, I will double check with @madisongh concerning the SDcard flashing process.

**Comment by madisongh** [comment]
I spent some time looking at this today.  Even stock L4T doesn't really support SDcard booting for the Xavier "out of the box", and even the not-very-clear instructions I've seen in various forum posts and on eLinux aren't working for me, at least with recent versions of L4T.

Now as for OE/Yocto builds... you can easily append ` root=/dev/mmcblk1p1` to the KERNEL_ARGS setting to direct the kernel to use the SDcard for the rootfs.  We don't implement the `extlinux.conf` setup that they have in L4T on the cboot-based platforms, but adding support for it would probably make it easier to handle SDcard booting. I'm not sure yet whether we could get it to work without it, but maybe.

In any case, there's some more work involved for this.

**Comment by madisongh** [comment]
I have managed to put together some changes to split the kernel/DTB/rootfs partitions out to an SDcard, and it appears to work OK for simple use cases, at least. PR #643 has the changes.  I've tried them with a build off master (R32.5.1), and patched them over to dunfell-l4t-r32.4.3 (they patch cleanly). If folks who need this functionality could give them a try, I'd appreciate any feedback.

**Comment by ichergui** [comment]
Hey @madisongh 
Thanks for the changes, I have a quick question:
How `cboot` will deal when SDcard is plugged ? Is the booting sequence automatically try the SDcard then eMMC ? 
Have we to make updates in `KERNEL_ARGS` (root=`/dev/mmcblk1p1`).

I'm trying it without any changes in the `KERNEL_ARGS`, I will let you know.

**Comment by madisongh** [comment]
Yes, by default cboot checks the SDcard before the eMMC when loading the kernel.  And the default initramfs we provide looks for the APP partition by name, so you don't need the `root=` in KERNEL_ARGS.

**Comment by ichergui** [comment]
Thanks @madisongh to make this available, I tested it and it works fine to me.
Well done
