### ISSUE TITLE
R32.6.1-t210: gpu_burn test fails

### ISSUE THREAD

**Issue by madisongh** [OE4T/meta-tegra#769]
**Describe the bug**
Testing on wip-dunfell-l4t-r32.6, jetson-nano-emmc, core-image-sato.

The `gpu_burn` test hangs without displaying any progress.  Process must be manually killed to exit the test.

The same test does work OK on TX2 and Xavier.

Needs investigation.

**Comment by ichergui** [comment]
Hey @madisongh 
Could you please share the command line that you used here ?

**Comment by madisongh** [comment]
```
cd /opt/cudatests/cpu_burn
./gpu_burn
```

**Comment by ichergui** [comment]
This is working fine on `Jetson Xavier AGX`

**Comment by madisongh** [comment]
Yes, it was only on the Nano I had the problem, as I mentioned.

**Comment by madisongh** [comment]
I re-ran this with a fresh build and didn't encounter the hanging problem, so this was probably an issue with the environment I had at the time.  Closing.
