### ISSUE TITLE
nvidia-l4t-jetson-multimedia-api for t210 not found

### ISSUE THREAD

**Issue by FSX** [OE4T/meta-tegra#791]
After this commit: https://github.com/OE4T/meta-tegra/commit/04057f1ae829c9a5ddc5daebfb2299ea3fadca35. Our build fails as the URL to `nvidia-l4t-jetson-multimedia-api_32.5.1-20210519111140_arm64.deb` results in a 404. In on this page https://repo.download.nvidia.com/jetson/#Jetpack%204.5 I can't find the file for t210.

**To Reproduce**
1. Build `meta-tegra` branch `dunfell-l4t-r32.5.0` with `jetson-nano-devkit` based on `t210`
2. Build with bitbake argument `core-image-x11`
3. ~Deploy to hardware with method '...'~
4. ~See error '...' with link to any relevant logs at '...'~

**Comment by madisongh** [comment]
Ah, right, I forgot to set L4T_DEB_SOCNAME in the recipe, and I've got the package in my PREMIRROR so it didn't trigger the miss.   Will get that fixed.

**Comment by madisongh** [comment]
OK, I've updated all the branches that have that change.  Pull in the latest and let me know if you still see the issue.

**Comment by FSX** [comment]
Seems to build. Thanks. :+1:
