### ISSUE TITLE
imx8m-iwg33m  - bitbake imx-image-full  error

### ISSUE THREAD

**Issue by hjmagadum2002** [OE4T/meta-tegra#801]
Ubuntu 18.04.  Please le me know how I cab solve

hemantjjsm@hemant-VPC:~/iwg33m-yocto-bsp/build_iwg33m$ bitbake imx-image-full 
Loading cache: 100% |######################################| Time: 0:00:01 
Loaded 4649 entries from dependency cache. 
Parsing recipes: 100% |####################################| Time: 0:00:02 
Parsing of 3227 .bb files complete (3226 cached, 1 parsed). 4650 targets, 224 skipped, 1 masked, 0 errors. 
NOTE: Resolving any missing task queue dependencies 

Build Configuration: 
BB_VERSION           = "1.44.0" 
BUILD_SYS            = "x86_64-linux" 
NATIVELSBSTRING      = "ubuntu-18.04" 
TARGET_SYS           = "aarch64-poky-linux" 
MACHINE              = "imx8m-iwg33m" 
DISTRO               = "fsl-imx-xwayland" 
DISTRO_VERSION       = "5.4-zeus" 
TUNE_FEATURES        = "aarch64 cortexa53 crc crypto" 
TARGET_FPU           = "" 
meta                  
meta-poky            = "HEAD:d88d62c20d7d8da85f02edb170dae0280624ad7e" 
meta-oe               
meta-multimedia       
meta-python          = "HEAD:2b5dd1eb81cd08bc065bc76125f2856e9383e98b" 
meta-freescale       = "HEAD:14f1a630a47375432f93c556927b879b51d84c4e" 
meta-freescale-3rdparty = "HEAD:dbcc686f52c3c84db8cb86aa8973a4e373651b98" 
meta-freescale-distro = "HEAD:ca27d12e4964d1336e662bcc60184bbff526c857" 
meta-bsp              
meta-sdk              
meta-ml              = "HEAD:63665ab70ca609451533101cded2a620b340768c" 
meta-nxp-demo-experience = "HEAD:c7263d9f3cc7bbf44e7164ffeda494cf283d3dec" 
meta-browser         = "HEAD:ee3be3b5986a4aa0e73df2204a625ae1fe5df37e" 
meta-rust            = "HEAD:53bfa324891966a2daf5d36dc13d4a43725aebed" 
meta-clang           = "HEAD:711e593d5984aad3bf35c51b7ac4482982bc16c7" 
meta-gnome            
meta-networking       
meta-filesystems     = "HEAD:2b5dd1eb81cd08bc065bc76125f2856e9383e98b" 
meta-qt5             = "HEAD:21ce4c124d9a972d9122f87c64ac2773bf04c284" 
meta-python2         = "HEAD:4400f9155ec193d028208cf0c66aeed2ba2b00ab" 
meta-iwave           = "<unknown>:<unknown>" 

Initialising tasks: 100% |#################################| Time: 0:00:05 
Sstate summary: Wanted 2 Found 0 Missed 2 Current 3720 (0% match, 99% complete) 
NOTE: Executing Tasks 
NOTE: Setscene tasks completed 
ERROR: imx-image-full-1.0-r0 do_rootfs: The postinstall intercept hook 'update_gtk_immodules_cache' failed, details in /home/hemantjjsm/iwg33m-yocto-bsp/build_iwg33m/tmp/work/imx8m_iwg33m-poky-linux/imx-image-full/1.0-r0/temp/log.do_rootfs 
ERROR: Logfile of failure stored in: /home/hemantjjsm/iwg33m-yocto-bsp/build_iwg33m/tmp/work/imx8m_iwg33m-poky-linux/imx-image-full/1.0-r0/temp/log.do_rootfs.30466 
ERROR: Task (/home/hemantjjsm/iwg33m-yocto-bsp/sources/meta-imx/meta-sdk/dynamic-layers/qt5-layer/recipes-fsl/images/imx-image-full.bb:do_rootfs) failed with exit code '1' 
NOTE: Tasks Summary: Attempted 9823 tasks of which 9822 didn't need to be rerun and 1 failed. 

Summary: 1 task failed: 
  /home/hemantjjsm/iwg33m-yocto-bsp/sources/meta-imx/meta-sdk/dynamic-layers/qt5-layer/recipes-fsl/images/imx-image-full.bb:do_rootfs 
Summary: There was 1 ERROR message shown, returning a non-zero exit code.

**Comment by madisongh** [comment]
I don't see meta-tegra in your build setup, and you aren't building for one of the platforms this layer supports. I'd suggest asking for help on the mailing list for meta-freescale.
