### ISSUE TITLE
Error adding layers for nvidia docker container using dunfell

### ISSUE THREAD

**Issue by abhishekcodework** [OE4T/meta-tegra#820]
Got the following error when I tried to add layers for NVIDIA docker using the documentation from https://developer.ridgerun.com/wiki/index.php?title=Yocto_Support_for_NVIDIA_Jetson_Platforms_-_DeepStream#NVIDIA_Docker_Container

ERROR:-
NOTE: Starting bitbake server...
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/abhi/yocto-tegra/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 6335 at 2021-10-18 18:12:34.262200 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)

ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/abhi/yocto-tegra/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 6335 at 2021-10-18 18:12:34.262200 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)

abhi@system-818:~/yocto-tegra/build$ bitbake-layers add-layer ../meta-openembedded/meta-filesystems/
NOTE: Starting bitbake server...
ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/abhi/yocto-tegra/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 6340 at 2021-10-18 18:12:34.543018 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)

ERROR: Unable to start bitbake server (None)
ERROR: Server log for this session (/home/abhi/yocto-tegra/build/bitbake-cookerdaemon.log):
--- Starting bitbake server pid 6340 at 2021-10-18 18:12:34.543018 ---
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)
ERROR: Layer openembedded-layer is not compatible with the core layer which only supports these series: dunfell (layer is compatible with honister)

**Comment by ichergui** [comment]
Hey @abhishekcodework 

Are you using our  [tegra-demo-distro](https://github.com/OE4T/tegra-demo-distro) ?
`Docker` should work fine when using `dunfell` branch
BTW, we are waiting for updates from Nvidia concerning `Deepstream-6.0` because we had some issues with `deepstream-5.1`
Please check the discussions below 
* [tegra discussion 779](https://github.com/OE4T/meta-tegra/discussions/779) 
* [tegra discussion 146](https://github.com/OE4T/tegra-demo-distro/discussions/146)

**Comment by ichergui** [comment]
You can use our [tegra-demo-distro](https://github.com/OE4T/tegra-demo-distro) to start with.
* [Which branch should I use?](https://github.com/OE4T/meta-tegra/wiki/Which-branch-should-I-use%3F)

you should use `demo-image-full` to get what you are mentioning above (check the `README.md` file).

**Comment by abhishekcodework** [comment]
Thanks a lot for the help. I was able to create a .tar.gz Yocto image following the links you shared. I wanted to flash my device for /home dir and keep files from other directories as persistent data. How can I do this?

**Comment by madisongh** [comment]
> I wanted to flash my device for /home dir and keep files from other directories as persistent data. How can I do this?

I'm not exactly sure what you're asking here.  Can you explain a bit further?

**Comment by ichergui** [comment]
> Thanks a lot for the help. I was able to create a .tar.gz Yocto image following the links you shared. I wanted to flash my device for /home dir and keep files from other directories as persistent data. How can I do this?

Hey @abhishekcodework 

Any updates about this ticket. 
Did you manage to fix your issue ?

**Comment by abhishekcodework** [comment]
I was planning to use OTA updates to my device image using Device Update for Azure IoT Hub. We have certain packages and network certificates on the device which want to not lose when the new image is flashed on it. A solution is to partition the device and keep certs and packages in a partition that doesn't get affected during reflashing. Needed help on how to go about this.

**Comment by madisongh** [comment]
I don't know anything about Azure IoT Hub, but the demo distro that @ichergui pointed you to above has a setup for Mender, which does OTA updates. There are flash layouts with A/B partitions for the rootfs images, and a separate partition for storing data that needs to persist across upgrades.  You might be able to use that as a starting point, and open a [discussion](https://github.com/OE4T/tegra-demo-distro/discussions) in that repo if you have questions.

As this has gone off-topic from the original problem (which appears to be resolved), I'm going to close this issue now.
