### ISSUE TITLE
Container issues with honister and later branches

### ISSUE THREAD

**Issue by madisongh** [OE4T/meta-tegra#857]
Since OE-Core upgraded glibc to version 2.34, NVIDIA pre-built containers that rely on the Jetson library passthrough mechanism will see application failures, due to mismatches between the host-side libraries being exposed to the container and the older glibc inside the container.

This has always been a risk with the passthrough mechanism, and while we've been able to implement some workarounds for similar issues in the past, it's unlikely we'll be able to do so for this one.

**Comment by dwalkes** [comment]
Related discussion thread at https://matrix.to/#/!mKaltPMAHUgQwPUKcH:gitter.im/$O6KhBIqTWBRML8F5YSk3supKrPKWPFLp6F2A7p3DnyY?via=gitter.im&via=matrix.org&via=0m.ax
