### ISSUE TITLE
doscard.sh doesn't program all required partitions on Jetson Nano

### ISSUE THREAD

**Issue by tprrt** [OE4T/meta-tegra#917]
**Describe the bug**
I built a tegraflash package for Jetson Nano and another one for Jetson Xavier
NX, to program the SDcard contents directly onto the card from your development
host, so it worked on Xavier NX but not on Nano.

Some required partitions are missing from the Nano SDcard, only the root partition
seems written:

```
Device         Start      End  Sectors Size Type
/dev/mmcblk0p1  2048 29362175 29360128  14G Linux filesystem
```

While the result should be this, like on Xavier NX:

```
Device          Start      End  Sectors  Size Type
/dev/mmcblk0p1  28672 26765311 26736640 12.7G Linux filesystem
/dev/mmcblk0p2   2048     2303      256  128K Linux filesystem
/dev/mmcblk0p3   4096     4991      896  448K Linux filesystem
/dev/mmcblk0p4   6144     7295     1152  576K Linux filesystem
/dev/mmcblk0p5   8192     8319      128   64K Linux filesystem
/dev/mmcblk0p6  10240    10623      384  192K Linux filesystem
/dev/mmcblk0p7  12288    13055      768  384K Linux filesystem
/dev/mmcblk0p8  14336    14463      128   64K Linux filesystem
/dev/mmcblk0p9  16384    17279      896  448K Linux filesystem
/dev/mmcblk0p10 18432    19327      896  448K Linux filesystem
/dev/mmcblk0p11 20480    22015     1536  768K Linux filesystem
/dev/mmcblk0p12 22528    22655      128   64K Linux filesystem
/dev/mmcblk0p13 24576    24959      384  192K Linux filesystem
/dev/mmcblk0p14 26624    26879      256  128K Linux filesystem
```

**To Reproduce**

I only use the 'honister' branch of `meta-tegra` with the oe-core layer (meta)
and bitbake 1.52, to build 'core-image-minimal', to finally write the SDCard
with 'dosdcard.sh'.

```
bitbake core-image-minimal

Build Configuration:
BB_VERSION           = "1.52.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-nodistro-linux"
MACHINE              = "jetson-nano-devkit"
DISTRO               = "nodistro"
DISTRO_VERSION       = "3.4"
TUNE_FEATURES        = "aarch64 armv8a crc"
TARGET_FPU           = ""
meta                 = "HEAD:418a9c4c31615a9e3e011fc2b21fb7154bc6c93a"
meta-tegra           = "HEAD:e28a08d63c66563cc41ba57d0bb58b6be2c5d32c"
```

```
sudo ./dosdcard.sh /dev/mmcblk0 -y

Board ID(3448) version(200) SKU() revision() from environment
Welcome to Tegra Flash
version 1.0.0
Type ? or help for help and q or quit to exit
Use ! to execute system commands

[   0.0022 ] Using default ramcode: 0
[   0.0022 ] Disable BPMP dtb trim, using default dtb
[   0.0022 ]
[   0.0042 ] tegrasign --getmode mode.txt --key None
[   0.0048 ] Assuming zero filled SBK key
[   0.0049 ]
[   0.0054 ] Generating RCM messages
[   0.0072 ] tegrarcm --listrcm rcm_list.xml --chip 0x21 0 --download rcm nvtboot_recovery.bin 0 0
[   0.0078 ] RCM 0 is saved as rcm_0.rcm
[   0.0081 ] RCM 1 is saved as rcm_1.rcm
[   0.0081 ] List of rcm files are saved in rcm_list.xml
[   0.0081 ]
[   0.0081 ] Signing RCM messages
[   0.0098 ] tegrasign --key None --list rcm_list.xml --pubkeyhash pub_key.key
[   0.0105 ] Assuming zero filled SBK key
[   0.0142 ]
[   0.0142 ] Copying signature to RCM mesages
[   0.0159 ] tegrarcm --chip 0x21 0 --updatesig rcm_list_signed.xml
[   0.0168 ]
[   0.0168 ] Parsing partition layout
[   0.0185 ] tegraparser --pt flash.xml.tmp
[   0.0194 ]
[   0.0194 ] Creating list of images to be signed
[   0.0211 ] tegrahost --chip 0x21 0 --partitionlayout flash.xml.bin --list images_list.xml
[   0.0237 ]
[   0.0238 ] Generating signatures
[   0.0256 ] tegrasign --key None --list images_list.xml --pubkeyhash pub_key.key
[   0.0263 ] Assuming zero filled SBK key
[   0.0662 ]
[   0.0662 ] Generating br-bct
[   0.0682 ] tegrabct --bct jetson-nano-devkit.cfg --chip 0x21 0
[   0.0712 ]
[   0.0712 ] Updating boot device parameters
[   0.0728 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --updatedevparam flash.xml.bin
[   0.0735 ] Warning: No sdram params
[   0.0737 ]
[   0.0737 ] Updating bl info
[   0.0753 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --updateblinfo flash.xml.bin --updatesig images_list_signed.xml
[   0.0764 ]
[   0.0764 ] Updating secondary storage information into bct
[   0.0782 ] tegraparser --pt flash.xml.bin --chip 0x21 0 --updatecustinfo jetson-nano-devkit.bct
[   0.0788 ]
[   0.0789 ] Updating Odmdata
[   0.0805 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --updatefields Odmdata =0xA4000
[   0.0812 ] Warning: No sdram params
[   0.0813 ]
[   0.0813 ] Get Signed section of bct
[   0.0829 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --listbct bct_list.xml
[   0.0836 ]
[   0.0836 ] Signing BCT
[   0.0869 ] tegrasign --key None --list bct_list.xml --pubkeyhash pub_key.key
[   0.0875 ] Assuming zero filled SBK key
[   0.0879 ]
[   0.0879 ] Updating BCT with signature
[   0.0896 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --updatesig bct_list_signed.xml
[   0.0904 ]
[   0.0905 ] Copying signatures
[   0.0922 ] tegrahost --chip 0x21 0 --partitionlayout flash.xml.bin --updatesig images_list_signed.xml
[   0.0952 ]
[   0.0953 ] Updating BFS information on BCT
[   0.0970 ] tegrabct --bct jetson-nano-devkit.bct --chip 0x21 0 --updatebfsinfo flash.xml.bin
[   0.0977 ]
[   0.0977 ] Copying signed file in tegraflash/signed
Init...APP...[OK]
Writing...APP...[OK: /dev/mmcblk0]
```

**Comment by madisongh** [comment]
As described [on the wiki](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit#spi-flash-on-sdcard-based-kits), if this is the first time you are setting things up on a Nano dev kit (either ever, or if you're upgrading between L4T versions that involve a flash layout change), you must program the bootloader partitions in the SPI flash to match up with the SDcard contents.

It looks like your current bootloader is for an older release.  In L4T-R32.5.x, the Nano dev kits were changed to move all bootloader partitions into the SPI flash.  Re-flashing should take care of the problem.

**Comment by tprrt** [comment]
> As described [on the wiki](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit#spi-flash-on-sdcard-based-kits), if this is the first time you are setting things up on a Nano dev kit (either ever, or if you're upgrading between L4T versions that involve a flash layout change), you must program the bootloader partitions in the SPI flash to match up with the SDcard contents.
> 
> It looks like your current bootloader is for an older release. In L4T-R32.5.x, the Nano dev kits were changed to move all bootloader partitions into the SPI flash. Re-flashing should take care of the problem.

Hello @madisongh,

- How many partitions should the SDCard contain when written with dosdcard.sh?
Currently there is only one, the rootfs partition. 
- Is it possible as the Xavier NX to flash the bootloader content on the SDCard?

Best regards,
Thomas

**Comment by madisongh** [comment]
With L4T R32.5.x and later, there is just the APP partition on the SDcard.  As I said, all of the boot partitions got moved to the SPI flash.

The Nano is different from the Xavier NX - each Jetson model has its own particular flash layout.

**Comment by tprrt** [comment]
Hello @madisongh ,

> With L4T R32.5.x and later, there is just the APP partition on the SDcard. As I said, all of the boot partitions got moved to the SPI flash.
> 
> The Nano is different from the Xavier NX - each Jetson model has its own particular flash layout.

I noted, thank you for your help.

So, I  reprogrammed the bootloader partitions in the SPI flash then the SDCard is now successfully read.

Best regards,
Thomas Perrot
