### ISSUE TITLE
Blank screen with Qt5 (EGLFS + KMS/DRM) since 32.7.1

### ISSUE THREAD

**Issue by benediktley** [OE4T/meta-tegra#956]
Since L4T32.7.1 (dunfell branch) my Qt application does not render any more. 
The application is starting and interaction with mouse/keyboard/touch is working but the screen is black. No issues on previous L4T32.6.1 branch. I do not use X11 or wayland, both are disabled.

Qt installation from [meta-qt5](https://github.com/meta-qt5/meta-qt5) (tested both, dunfell & master)
`PACKAGECONFIG_append_qtbase = " eglfs kms gles2 "`

runtime environment variables:
`QT_QPA_PLATFORM=eglfs`
`QT_QPA_EGLFS_INTEGRATION=eglfs_kms_egldevice`

Qt sample application:
[https://github.com/alpqr/quickmwtest](https://github.com/alpqr/quickmwtest)

**Comment by kekiefer** [comment]
Confirming that I'm seeing the same with qt5's egldevice and 32.7.1 on the master branch. It's worth noting that qt5 isn't receiving updates anymore an there's a possibility of fixes upstream in qt6, but I haven't looked. Patching qt5's egldevice integration work with tegra-udrm is another avenue to explore. Do you know if NVIDIA's jetpack release works with qt5?

**Comment by benediktley** [comment]
Just did a brief test on the latest jetpack release (4.6.1) and run the sample application. Had some issues compiling qt, so i did the test with the prebuilt deb version from repo (qt5.9.5). Same issue here: Application runs without any error but the screen remains black.

I'm testing the whole thing again with Qt6 but won't have time until next week as I'm travelling for a few days.

**Comment by kekiefer** [comment]
I think I have a solution to this. It appears that the newer nvidia libdrm is rejecting the calls to `drmModeSetCrtc` with the framebuffer id `-1`, which was accepted before to allow qt to perform modesetting without flipping buffers (which was left to the egl). I can set up a dummy framebuffer to flip initially, and then things are happy. Patches are forthcoming.
