### ISSUE TITLE
Undefined variable board_id at tegra194-flash-helper.sh

### ISSUE THREAD

**Issue by jloaiza** [OE4T/meta-tegra#969]
**Describe the bug**
At branch `dunfell-l4t-r32.6.1`, `tegra194-flash-helper.sh` is using an undefined variable: `$board_id` possible typo of `$boardid`. Because of this, the ramcode is not properly set.

``` 
if [ "$board_id" = "2888" -a "$board_sku" = "0004" ]; then
    # 32GB AGX Xavier
    ramcodeargs="--ramcode 2"
elif [ "$board_id" = "3668" -a "$board_version" = "301" ]; then
    # Xavier NX A03
    ramcodeargs="--ramcode 1"
fi
```
https://github.com/OE4T/meta-tegra/blob/dunfell-l4t-r32.6.1/recipes-bsp/tegra-binaries/tegra-helper-scripts/tegra194-flash-helper.sh#L234-L240

**Comment by madisongh** [comment]
Yup, it's a typo.  I've pushed a fix to that branch, and a similar fix to the 32.7.1-based branches.
Thanks for raising the issue!
