### ISSUE TITLE
kernel-image-* erroneously included in rootfs (kirkstone and later)

### ISSUE THREAD

**Issue by kekiefer** [OE4T/meta-tegra#999]
As of commit https://github.com/openembedded/openembedded-core/commit/1c90b27d2c65cfb4f9debf0272820b6a95942f76 the kernel images are included in the rootfs, as the meta-tegra layer needs to be updated to either:

a) replace the linux-tegra recipe's existing fixup to `RDEPENDS` with a fixup to `RRECOMMENDS` instead
b) remove the fixup and add a `PACKAGE_EXCLUDE:append` to the tegra-common.inc

I've tested both approaches, and both will work. So this issue is to solicit feedback regarding which path makes more sense.

**Comment by madisongh** [comment]
Option (a) looks better to me.   The PACKAGE_EXCLUDE approach looks more difficult to override for cases where someone _does_ want the kernel image included in the rootfs.

**Comment by ichergui** [comment]
Hey @kekiefer 
I prefer option a. I think it is the appropriate way  as a fix 
Thanks for catching this :blush:
